import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bruno Angeloti</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.header}>
        
      </div>
      <div className={styles.section}>
        <div className={styles.content}>
          <h1>BRUNO ANGELOTI</h1>
          <h2>Estudante de engenharia de computação - UFES</h2>
        </div>
        <div className={styles.image}>
          <img src="person.svg" alt="pessoa no computador" />
        </div>
      </div>
      
    </div>
  )
}
